In [1]:
import pandas as pd
import numpy as np

In [37]:
x1 = np.arange(-10, 10, 3)
x2 = np.arange(-3, 5, 1.3)

In [38]:
x1

array([-10,  -7,  -4,  -1,   2,   5,   8])

In [39]:
x2

array([-3. , -1.7, -0.4,  0.9,  2.2,  3.5,  4.8])

In [40]:
def realfunction(x1,x2):
    return x1**2 + (x2 / 2)

In [41]:
y = realfunction(x1,x2)

In [42]:
y

array([98.5 , 48.15, 15.8 ,  1.45,  5.1 , 26.75, 66.4 ])